export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as PreFooter} from './prefooter/PreFooter'
export {default as SideNav} from './sidenav/SideNav'
export {default as Display} from './display/Display'
export {default as About} from './about/About'
export {default as Notice} from './notice/Notice'
export {default as Sports} from './activities/sports/Sports'
export {default as Word} from './word/Word'

export {default as ContactUs} from './contactUs/ContactUs'
export {default as Admission} from './admission/Admission'
export {default as Quotes} from './quotes/Quotes'
export {default as School} from './school/School'
export {default as Posters} from './posters/Posters'
